Rename additional KDE strings

diff --git a/starttde b/starttde
--- a/starttde
+++ b/starttde
@@ -111,9 +111,9 @@ else
 fi
 
 # Run a quick test for root.
-if [ -z "$KDEROOTHOME" ] && [ "$UID" = "0" ]; then
-  echo "[starttde] User ID is $UID. Setting KDEROOTHOME to $TDEHOME."
-  export KDEROOTHOME=$TDEHOME
+if [ -z "$TDEROOTHOME" ] && [ "$UID" = "0" ]; then
+  echo "[starttde] User ID is $UID. Setting TDEROOTHOME to $TDEHOME."
+  export TDEROOTHOME=$TDEHOME
 fi
 
 # Modify the following environment variables only as necessary.
@@ -162,18 +162,18 @@ if [ -d /opt/trinity ]; then
   fi
 fi
 
-test -n "$TDEHOME" && kdehome=`echo "$TDEHOME" | sed "s,^~/,$HOME/,"`
-echo "[starttde] kdehome: $kdehome" 1>&2
+test -n "$TDEHOME" && tdehome=`echo "$TDEHOME" | sed "s,^~/,$HOME/,"`
+echo "[starttde] tdehome: $tdehome" 1>&2
 
 # Allow interested applications, such as the Plasma control wrapper,
 # to know that this is a Trinity desktop and not a KDE one.
 export DESKTOP_SESSION=trinity
 
 # Please see kstartupconfig source for usage.
-mkdir -m 700 -p $kdehome
-mkdir -m 700 -p $kdehome/share
-mkdir -m 700 -p $kdehome/share/config
-cat >$kdehome/share/config/startupconfigkeys <<EOF
+mkdir -m 700 -p $tdehome
+mkdir -m 700 -p $tdehome/share
+mkdir -m 700 -p $tdehome/share/config
+cat >$tdehome/share/config/startupconfigkeys <<EOF
 kcminputrc Mouse cursorTheme ''
 kcminputrc Mouse cursorSize ''
 kpersonalizerrc General FirstLogin true
@@ -189,16 +189,16 @@ kstartupconfig
 if test $? -ne 0; then
   xmessage -geometry 500x100 "Could not start kstartupconfig. Check your installation."
 fi
-# $kdehome/share/config/startupconfig should exist but avoid script failure if not.
-if [ -r $kdehome/share/config/startupconfig ]; then
-  . $kdehome/share/config/startupconfig
+# $tdehome/share/config/startupconfig should exist but avoid script failure if not.
+if [ -r $tdehome/share/config/startupconfig ]; then
+  . $tdehome/share/config/startupconfig
 fi
 
 # Make sure a default wallpaper is set.
-if [ ! -e $kdehome/share/config/kdesktoprc ]; then
+if [ ! -e $tdehome/share/config/kdesktoprc ]; then
  # With Trinity KDE this file should exist, but test first.
   if [ -r /usr/share/wallpapers/isadora.png.desktop ]; then
-cat >$kdehome/share/config/kdesktoprc <<EOF
+cat >$tdehome/share/config/kdesktoprc <<EOF
 [Desktop0]
 Wallpaper=isadora.png
 WallpaperMode=Scaled
@@ -293,21 +293,21 @@ fi
 # Configuration of the gtk_qt_engine if not already set.
 
 if test -n "$TDEDIRS"; then
-  kdedirs_first=`echo "$TDEDIRS" | sed -e 's/:.*//'`
-  KGTK_RC_ENGINE=$kdedirs_first/share/kgtk/gtk-qt-engine.rc.sh
-  KGTK_RC_KDE1=$kdedirs_first/share/kgtk/.gtkrc-2.0-kde4
-  KGTK_RC_KDE2=$kdedirs_first/share/kgtk/.gtkrc-2.0-kde-kde4
+  tdedirs_first=`echo "$TDEDIRS" | sed -e 's/:.*//'`
+  KGTK_RC_ENGINE=$tdedirs_first/share/kgtk/gtk-qt-engine.rc.sh
+  KGTK_RC_KDE1=$tdedirs_first/share/kgtk/.gtkrc-2.0-kde4
+  KGTK_RC_KDE2=$tdedirs_first/share/kgtk/.gtkrc-2.0-kde-kde4
 else
   KGTK_RC_ENGINE=$TDEDIR/share/kgtk/gtk-qt-engine.rc.sh
   KGTK_RC_KDE1=$TDEDIR/share/kgtk/.gtkrc-2.0-kde4
   KGTK_RC_KDE2=$TDEDIR/share/kgtk/.gtkrc-2.0-kde-kde4
 fi
 
-if [ ! -e $kdehome/env/gtk-qt-engine.rc.sh ] && [ -e $KGTK_RC_ENGINE ]
+if [ ! -e $tdehome/env/gtk-qt-engine.rc.sh ] && [ -e $KGTK_RC_ENGINE ]
 then
- mkdir -p $kdehome/env
- cp -f $KGTK_RC_ENGINE $kdehome/env
- chmod 755 $kdehome/env/gtk-qt-engine.rc.sh
+ mkdir -p $tdehome/env
+ cp -f $KGTK_RC_ENGINE $tdehome/env
+ chmod 755 $tdehome/env/gtk-qt-engine.rc.sh
 fi
 
 if [ ! -e $HOME/.gtkrc-2.0-kde4 ] && [ -e $KGTK_RC_KDE1 ]
@@ -391,20 +391,20 @@ echo "[starttde] TDEDIR: $TDEDIR" 1>&2
 echo "[starttde] TDEDIRS: $TDEDIRS" 1>&2
 
 if test -n "$TDEDIRS"; then
-  kdedirs_first=`echo "$TDEDIRS" | sed -e 's/:.*//'`
-  sys_odir=$kdedirs_first/share/fonts/override
-  sys_fdir=$kdedirs_first/share/fonts
+  tdedirs_first=`echo "$TDEDIRS" | sed -e 's/:.*//'`
+  sys_odir=$tdedirs_first/share/fonts/override
+  sys_fdir=$tdedirs_first/share/fonts
 else
   sys_odir=$TDEDIR/share/fonts/override
   sys_fdir=$TDEDIR/share/fonts
 fi
 
 if test -n "$TDEDIRS"; then
-  kdedirs_first=`echo "$TDEDIRS" | sed -e 's/:.*//'`
-  echo "[starttde] kdedirs_first: $kdedirs_first"
-  if [ -r $kdedirs_first/share/kgtk/preload ]; then
-    echo "[starttde] Reading from $kdedirs_first/share/kgtk/preload"
-    read -r KGTK_PRELOAD < $kdedirs_first/share/kgtk/preload
+  tdedirs_first=`echo "$TDEDIRS" | sed -e 's/:.*//'`
+  echo "[starttde] tdedirs_first: $tdedirs_first"
+  if [ -r $tdedirs_first/share/kgtk/preload ]; then
+    echo "[starttde] Reading from $tdedirs_first/share/kgtk/preload"
+    read -r KGTK_PRELOAD < $tdedirs_first/share/kgtk/preload
   fi
 else
   if [ -r $TDEDIR/share/kgtk/preload ]; then
@@ -498,9 +498,9 @@ if test "$kpersonalizerrc_general_firstlogin" = "true"; then
 fi
 
 # Remove moodin cache if we have a new wallpaper installed, jriddell. Distro-specific.
-if [ -d $kdehome/share/apps/ksplash/cache/Moodin/kubuntu ]; then
-  if [ /usr/share/wallpapers/kubuntu-wallpaper.png -nt $kdehome/share/apps/ksplash/cache/Moodin/kubuntu/ ]; then
-    rm -rf $kdehome/share/apps/ksplash/cache/Moodin/kubuntu/
+if [ -d $tdehome/share/apps/ksplash/cache/Moodin/kubuntu ]; then
+  if [ /usr/share/wallpapers/kubuntu-wallpaper.png -nt $tdehome/share/apps/ksplash/cache/Moodin/kubuntu/ ]; then
+    rm -rf $tdehome/share/apps/ksplash/cache/Moodin/kubuntu/
   fi
 fi
 
@@ -534,7 +534,7 @@ fi
 #     xprop -root | grep "^TDE_FULL_SESSION" >/dev/null 2>/dev/null
 #     if test $? -eq 0; then ... whatever
 #
-# Additionally there is (since KDE 3.5.7) $KDE_SESSION_UID with the uid
+# Additionally there is (since KDE 3.5.7) $TDE_SESSION_UID with the uid
 # of the user running the KDE session. It should be rarely needed (e.g.
 # after sudo to prevent desktop-wide functionality in the new user's kded).
 #
@@ -542,9 +542,9 @@ TDE_FULL_SESSION=true
 export TDE_FULL_SESSION
 xprop -root -f TDE_FULL_SESSION 8t -set TDE_FULL_SESSION true
 echo "[starttde] TDE_FULL_SESSION: $TDE_FULL_SESSION" 1>&2
-KDE_SESSION_UID=$UID
-export KDE_SESSION_UID
-echo "[starttde] KDE_SESSION_UID: $KDE_SESSION_UID" 1>&2
+TDE_SESSION_UID=$UID
+export TDE_SESSION_UID
+echo "[starttde] TDE_SESSION_UID: $TDE_SESSION_UID" 1>&2
 
 # We set LD_BIND_NOW to increase the efficiency of tdeinit.
 # tdeinit unsets this variable before loading applications.
@@ -613,7 +613,7 @@ done
 
 unset TDE_FULL_SESSION
 xprop -root -remove TDE_FULL_SESSION
-unset KDE_SESSION_UID
+unset TDE_SESSION_UID
 
 # Initialize_Status_Header
 echo "[starttde] Trinity shutdown complete." 1>&2
